services:
  recipes_db:
    image: postgres:latest
    container_name: recipes_db
    environment:
      - POSTGRES_DB=recipesdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - recipes_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: recipes_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8080:8080'
    command:
      - start-dev

volumes:
  recipes_data:
    driver: local
    name: recipes_data
